task failIt << {
	throw new Exception("fail it anyway!")
}